name: Security SCA

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "gestor-contrasenas"
          path: "."
          format: "HTML,JSON"
          out: "reports"
          args: >-
            --enableRetired
            --failOnCVSS 8

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
